# config/_default/languages.nl.toml

languageCode = "nl"
languageName = "Nederlands"
languageDirection = "ltr"
weight = 1

title = "Robert van Bregt"
# copyright is used in internal RSS template
copyright = "&copy; 2003-2023 Robert van Bregt"

[author]
  # 'name' and 'email' are used in internal RSS template
  name = "Robert van Bregt"
  email = "contact.rjib@vanbregt.eu"
  ## for Congo: image in assets folder
  image = "img/profile.jpg" 
  links = [
    { mastodon = "https://mastodon.nl/@ro" },
    { twitter = "https://twitter.com/robertvanbregt" },
    { linkedin = "https://linkedin.com/in/robertvanbregt" },
    { github = "https://github.com/metbril" },
  ]

  headline = "Verbetert de wereld, maar begint bij zichzelf."
  bio = "Robert is een ervaren projectmanger in de zorg-ict. Is een privacyvoorvechter. Automatiseert zijn huis en zijn leven, omdat het kan. Heeft een fascinatie voor wetenschap en techniek."

[params]
  description = "De persoonlijke website van Robert van Bregt"
  dateFormat = "2 January 2006"

  # List sections with content for home page
  mainSections = [ "posts" ]
