# config/_default/languages.en.toml

languageCode = "en"
languageName = "English"
languageDirection = "ltr"
weight = 2

title = "Robert van Bregt"
# copyright is used in internal RSS template
copyright = "&copy; 2003-2023 Robert van Bregt"

[author]
  # 'name' and 'email' are used in internal RSS template
  name = "Robert van Bregt"
  email = "contact.rjib@vanbregt.eu"
  ## for Congo: image in assets folder
  image = "img/profile.jpg"
  links = [
    { mastodon = "https://mastodon.nl/@ro" },
    { twitter = "https://twitter.com/robertvanbregt" },
    { linkedin = "https://linkedin.com/in/robertvanbregt" },
    { github = "https://github.com/metbril" },
  ]

  headline = "Makes the world a little better, but himself first."
  bio = "Robert is an experienced projectmanger in health IT. Is een privacy advocate. Automates his home and his life, because he can. Is fascinated by sciency and technology."

[params]
  description = "The personal website of Robert van Bregt"
  dateFormat = "2 January 2006"

  # List sections with content for home page
  mainSections = [ "posts" ]
