# config/_default/params.toml

[author]
  # name and email are used in internal RSS template
  name  = "Robert van Bregt"
  email = "contact.rjib@vanbregt.eu"

  url   = "https://www.vanbregt.eu/"
  photo = "/img/photo.jpg"

[social]
  # Twitter meta card
  twitter = "robertvanbregt"

# ---------- Congo theme ----------

colorScheme = "slate"
autoSwitchAppearance = true

[article]
  showTaxonomies = true
  # showDate = true
  # showReadingTime = true

[list]
  groupByYear = false
  showSummary = true

[homepage]
  layout = "profile"
  showRecent = true

[header]
  layout = "basic"
  logo = "img/logo.png"

[footer]
  showAppearanceSwitcher = true
  showScrollToTop = true

# ---------- official and common parameters ----------

author      = "Robert van Bregt"
description = "Persoonlijke website van Robert van Bregt"
keywords    = "blog, persoonlijk"
images      = ["/img/avatar.jpg"]  # twitter cards
avatarURL   = "/img/avatar.jpg"
favicon     = "/favicon.ico"

# dateFormat = "2 January 2006"
dateFormat = "02-01-2006"

# See also post count
maxSeeAlsoItems = 5

commit = "https://github.com/metbril/robertvanbregt.nl/tree/"

rtl    = false

math   = false

# some markdown allowed
license = "Unless otherwise noted, all written content on this site is licenced with a [CC BY-SA 4.0 license](http://creativecommons.org/licenses/by-sa/4.0/)."
