# baseUrl = "https://www.robertvanbregt.nl/"
title = "Robert van Bregt"

languageCode = "nl-nl"
defaultContentLanguage = "nl"

theme = "coder"

paginate = 20
paginatePath = "pagina"
canonifyUrls = true

pluralizeListTitles = false

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = ""

metaDataFormat = "yaml"

[params]

  favicon = "/favicon.ico"

  # coder theme
 	author = "Robert van Bregt"
  info = "Projectmanager. Automagiseerder. Geek. Rotterdammert."
  description = "Persoonlijke website van Robert van Bregt"
  keywords = "blog, persoonlijk"
  footerContent = "Verbetert de wereld, maar begint bij zichzelf."

  avatarurl = "/images/robert-color.jpg"
  # gravatar = "contact@robertvanbregt.nl"

  colorScheme = "auto"
  custom_css = []
  custom_js = []
  enableTwemoji = true

  # Series see also post count
  maxSeeAlsoItems = 5


  dateFormat = "2 January 2006"

  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2003

  commit = "https://github.com/metbril/robertvanbregt.nl/tree/"

  rtl = false

  math = false

  [[params.social]]
      name = "LinkedIn"
      icon = "fab fa-linkedin"
      weight = 1
      url = "https://www.linkedin.com/in/robertvanbregt/"
  [[params.social]]
      name = "Twitter"
      icon = "fab fa-twitter"
      weight = 2
      url = "https://twitter.com/metbril/"
  [[params.social]]
      name = "Github"
      icon = "fab fa-github"
      weight = 3
      url = "https://github.com/metbril/"
  [[params.social]]
      name = "Gitlab"
      icon = "fab fa-gitlab"
      weight = 4
      url = "https://gitlab.com/metbril/"
  [[params.social]]
      name = "E-mail"
      icon = "fas fa-envelope"
      weight = 98
      url = "mailto:contact@robertvanbregt.nl"
  [[params.social]]
      name = "RSS"
      icon = "fas fa-rss"
      weight = 99
      url = "/index.xml"
      rel = "alternate"
      type = "application/rss+xml"

[menu]

  [[menu.main]]
    name = "Over"
    weight = 10
    url = "/over"

  [[menu.main]]
    name = "Nu"
    weight = 15
    url = "/nu"

  [[menu.main]]
    name = "Blog"
    weight = 20
    url = "/posts"

  [[menu.main]]
    identifier = "tags"
    name = "Labels"
    title = "Labels"
    url = "/tags"
    weight = 25

  [[menu.main]]
    name = "Projecten"
    weight = 30
    url = "/projecten"

  [[menu.main]]
    name = "Contact"
    weight = 40
    url = "/contact"

[languages]

    [languages.nl] # stub
      languageName = "🇳🇱"

    [languages.en]
        languageName = "🇬🇧"

        info = "Project manager. Automagician. Geek. Rotterdamned."
        description = "Personal website of Robert van Bregt"
        keywords = "blog, personal"
        footerContent = "Improves the world, but starts with himself."

        avatarUrl = "/images/robert-noir.jpg"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 10
            url = "/about"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 20
            url = "/posts"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 30
            url = "/projects"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 40
            url = "/contact"

# explicitly specify taxonomies for coder theme which supports series
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  posts = "/:year/:month/:day/:slug/"
  # https://gohugo.io/content-management/urls/#permalink-configuration-values
  # :year        | the 4-digit year
  # :month       | the 2-digit month
  # :monthname   | the name of the month
  # :day         | the 2-digit day
  # :weekday     | the 1-digit day of the week (Sunday = 0)
  # :weekdayname | the name of the day of the week
  # :yearday     | the 1- to 3-digit day of the year
  # :section     | the content’s section
  # :sections    | the content’s sections hierarchy
  # :title       | the content’s title
  # :slug        | the content’s slug (or title if no slug is provided in the front matter)
  # :filename    | the content’s filename (without extension)

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
