baseUrl   = "https://robertvanbregt.nl/"
title     = "Robert van Bregt"

# copyright is used in internal RSS template
copyright = "© Copyright Robert van Bregt 2003-2021"

theme = "grotius"

languageCode = "nl-nl"
defaultContentLanguage = "nl"

enableEmoji = true

# Lazy menu
# sectionPagesMenu = "main"

##################################################

# archetypeDir  = "archetypes"
# assetDir      = "assets"
# contentDir    = "content"
# configDir     = "config"
# datadir       = "data"
# layoutDir     = "layouts"
# publishDir    = "public"
# staticDir     = "static"
# themesDir     = "themes"

##################################################

# pagination
paginate     = 20         # default = 10
paginatePath = "pagina"   # default = "page"

canonifyUrls = true

pluralizeListTitles = false

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = ""
googleAnalytics = ""

# content front matter format
metaDataFormat = "yaml"

summaryLength = 70  # default 70

# name and email are used in internal RSS template
[author]
  name  = "Robert van Bregt"
  email = "contact@robertvanbregt.nl"

  url   = "https://robertvanbregt.nl/"
  photo = "/images/photo.jpg"

[social]
  twitter = "robertvanbregt"  # Used in internal Twitter meta card

[params]

  # ---------- official and common parameters ----------

 	author      = "Robert van Bregt"
  description = "Persoonlijke website van Robert van Bregt"
  keywords    = "blog, persoonlijk"
  images      = ["/img/avatar.jpg"]  # twitter cards
  avatarURL   = "/img/avatar.jpg"
  favicon     = "/favicon.ico"

  # List sections with content for home page
  mainSections = [ "posts" ]

  # dateFormat = "2 January 2006"
  dateFormat = "02-01-2006"

  # Series see also post count
  maxSeeAlsoItems = 5

  commit = "https://github.com/metbril/robertvanbregt.nl/tree/"

  rtl    = false

  math   = false

  # --- social icons for Grotius theme ---

  [[params.social]]
      name = "LinkedIn"
      icon = "fa fa-linkedin"
      weight = 1
      url = "https://www.linkedin.com/in/robertvanbregt/"
      rel = "me"
      color = "#0077b5"
  [[params.social]]
      name = "Twitter"
      icon = "fa fa-twitter"
      weight = 2
      url = "https://twitter.com/robertvanbregt/"
      rel = "me"
      color = "#1da1f2"
  [[params.social]]
      name = "Github"
      icon = "fa fa-github"
      weight = 11
      url = "https://github.com/metbril/"
      rel = "me"
      color = "#4183c4"
  [[params.social]]
      name = "Secure E-mail"
      icon = "fa fa-gnupg"
      weight = 97
      url = "/key.asc"
      color = "#0093DD"
  [[params.social]]
      name = "E-mail"
      icon = "fa fa-envelope"
      weight = 98
      url = "mailto:contact@robertvanbregt.nl"
      rel = "me"
  [[params.social]]
      name = "RSS"
      icon = "fa fa-rss"
      weight = 99
      url = "/index.xml"
      rel = "alternate"
      type = "application/rss+xml"
      color = "#f26522"

[menu]
  # Most menu items are defined in the front matter of that page.

# explicitly specify taxonomies for series support
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[services.rss]
  limit = 10

[permalinks]
  # Specify for each section (= folder name)
  posts = "/:year/:month/:day/:slug/"
  page = "/:slug/"

  # https://gohugo.io/content-management/urls/#permalink-configuration-values
  # :year        | the 4-digit year
  # :month       | the 2-digit month
  # :monthname   | the name of the month
  # :day         | the 2-digit day
  # :weekday     | the 1-digit day of the week (Sunday = 0)
  # :weekdayname | the name of the day of the week
  # :yearday     | the 1- to 3-digit day of the year
  # :section     | the content’s section
  # :sections    | the content’s sections hierarchy
  # :title       | the content’s title
  # :slug        | the content’s slug (or title if no slug is provided in the front matter)
  # :filename    | the content’s filename (without extension)
