baseUrl   = "https://robertvanbregt.nl/"
title     = "Robert van Bregt"

# copyright is used in internal RSS template
copyright = "© Copyright Robert van Bregt 2003-2021"

theme = "hugo-coder"

languageCode = "nl-nl"
defaultContentLanguage = "nl"

# Lazy menu
# sectionPagesMenu = "main"

##################################################

# archetypeDir  = "archetypes"
# assetDir      = "assets"
# contentDir    = "content"
# configDir     = "config"
# datadir       = "data"
# layoutDir     = "layouts"
# publishDir    = "public"
# staticDir     = "static"
# themesDir     = "themes"

##################################################

# pagination
paginate     = 10         # default = 10
paginatePath = "pagina"   # default = "page"

canonifyUrls = true

pluralizeListTitles = false

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = ""
googleAnalytics = ""

# content front matter format
metaDataFormat = "yaml"

summaryLength = 70  # default 70

# name and email are used in internal RSS template
[author]
  name  = "Robert van Bregt"
  email = "contact@robertvanbregt.nl"

  url   = "https://robertvanbregt.nl/"
  photo = "/images/photo.jpg"

[social]
  twitter = "robertvanbregt"  # Used in internal Twitter meta card

[params]

  # ---------- official and common parameters ----------

 	author      = "Robert van Bregt"
  description = "Persoonlijke website van Robert van Bregt"
  keywords = "blog, persoonlijk"

  favicon = "/favicon.ico"

  # Sections for home page content
  mainSections = ["posts"]

  enableTwemoji = true

  dateFormat = "2 January 2006"

  # ---------- SPECIFIC THEME VARIABLES hugo coder ----------
  info          = "Projectmanager. Automagiseerder. Geek. Rotterdammert."
  footerContent = "Verbetert de wereld en begint bij zichzelf."

  colorScheme   = "auto"
  custom_css    = []
  custom_js     = []

  # Series see also post count
  maxSeeAlsoItems = 5


  hideFooter    = false
  hideCredits   = false
  hideCopyright = false
  since         = 2003

  commit = "https://github.com/metbril/robertvanbregt.nl/tree/"

  rtl    = false

  math   = false

  [[params.social]]
      name = "LinkedIn"
      icon = "fa fa-linkedin"
      weight = 1
      url = "https://www.linkedin.com/in/robertvanbregt/"
      rel = "me"
      color = "#0077b5"
  [[params.social]]
      name = "Twitter"
      icon = "fa fa-twitter"
      weight = 2
      url = "https://twitter.com/robertvanbregt/"
      rel = "me"
      color = "#1da1f2"
  [[params.social]]
      name = "Mastodon"
      icon = "fa fa-mastodon"
      weight = 3
      url = "https://mastodon.social/@metbril"
      rel = "me"
      color = "#2b90d9"
  [[params.social]]
      name = "Github"
      icon = "fa fa-github"
      weight = 11
      url = "https://github.com/metbril/"
      rel = "me"
      color = "#4183c4"
  [[params.social]]
      name = "Gitlab"
      icon = "fa fa-gitlab"
      weight = 12
      url = "https://gitlab.com/metbril/"
      rel = "me"
      color = "#e2432a"
  [[params.social]]
      name = "Instagram"
      icon = "fa fa-instagram"
      weight = 21
      url = "https://instagram.com/robertvanbregt/"
      rel = "me"
      color = "#c32aa3"
  [[params.social]]
      name = "Flickr"
      icon = "fa fa-flickr"
      weight = 22
      url = "https://flickr.com/photos/rtvb/"
      rel = "me"
      color = "#f40083"
  [[params.social]]
      name = "Pocket"
      icon = "fa fa-get-pocket"
      weight = 31
      url = "https://getpocket.com/@metbril"
      rel = "me"
      color = "#ee4056"
  [[params.social]]
      name = "Reddit"
      icon = "fa fa-reddit"
      weight = 32
      url = "https://www.reddit.com/user/digineut"
      rel = "me"
      color = "#ff4500"
  [[params.social]]
      name = "Telegram"
      icon = "fa fa-telegram"
      weight = 33
      url = "https://t.me/robertvanbregt"
      rel = "me"
      color = "#0088cc"
  [[params.social]]
      name = "Trello"
      icon = "fa fa-trello"
      weight = 33
      url = "https://trello.com/metbril"
      rel = "me"
  [[params.social]]
      name = "E-mail"
      icon = "fa fa-gnupg"
      weight = 97
      url = "/key.asc"
      color = "#0093DD"
  [[params.social]]
      name = "E-mail"
      icon = "fa fa-envelope"
      weight = 98
      url = "mailto:contact@robertvanbregt.nl"
      rel = "me"
  [[params.social]]
      name = "RSS"
      icon = "fa fa-rss"
      weight = 99
      url = "/index.xml"
      rel = "alternate"
      type = "application/rss+xml"
      color = "#f26522"

[menu]
  # Most menu items are defined in the front matter of that page.

# explicitly specify taxonomies for coder theme which supports series
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  # Specify for each section (= folder name)
  posts = "/:year/:month/:day/:slug/"
  article = "/:year/:month/:day/:slug/"
  bladwijzers = "/:year/:month/:day/:slug/"
  likes = "/:year/:month/:day/:slug/"
  note = "/:year/:month/:day/:slug/"
  reacties = "/:year/:month/:day/:slug/"
  rsvps = "/:year/:month/:day/:slug/"
  # https://gohugo.io/content-management/urls/#permalink-configuration-values
  # :year        | the 4-digit year
  # :month       | the 2-digit month
  # :monthname   | the name of the month
  # :day         | the 2-digit day
  # :weekday     | the 1-digit day of the week (Sunday = 0)
  # :weekdayname | the name of the day of the week
  # :yearday     | the 1- to 3-digit day of the year
  # :section     | the content’s section
  # :sections    | the content’s sections hierarchy
  # :title       | the content’s title
  # :slug        | the content’s slug (or title if no slug is provided in the front matter)
  # :filename    | the content’s filename (without extension)

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[services.rss]
  limit = 10
