baseURL = "https://www.robertvanbregt.nl/"
title = "Robert van Bregt"
languageCode = "nl-nl"
copyright = "CC International"
theme = "ananke"

pluralizeListTitles = false

MetaDataFormat = "yaml"
DefaultContentLanguage = "nl"
SectionPagesMenu = "main"

[params]
  description = "Verbetert de wereld, maar begint bij zichzelf."
  recent_posts_number = 5
  favicon = "/favicon.ico"
  images = ["/img/avatar.png"]

  # Social profiles
  github = "https://github.com/metbril"
  gitlab = "htps://gitlab.com/metbril"
  instagram = "https://instagram.com/robertvanbregt"
  linkedin = "https://linkedin.com/in/robertvanbregt"
  medium = ""
  twitter = "https://twitter.com/robertvanbregt"
  youtube = ""
  
  # Ananke theme
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  artikel = "/:year/:month/:day/:slug/"
  bladwijzer = "/:year/:month/:day/:slug/"
  notitie = "/:year/:month/:day/:slug/"

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
