baseUrl = "https://robertvanbregt.nl/"
title = "Robert van Bregt"
copyright = "© Copyright Robert van Bregt 2003-2021"

languageCode = "nl-nl"
defaultContentLanguage = "nl"

# Lazy menu
# sectionPagesMenu = "main"

##################################################

# archetypeDir  = "archetypes"
# assetDir      = "assets"
# contentDir    = "content"
# configDir     = "config"
# datadir       = "data"
# layoutDir     = "layouts"
# publishDir    = "public"
# staticDir     = "static"
# themesDir     = "themes"

##################################################

theme = "grotius"

paginate = 10
canonifyUrls = true

pluralizeListTitles = false

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = ""
googleAnalytics = ""

# content front matter format
metaDataFormat = "yaml"

summaryLength = 20  # default 70

# name and email are used in internal RSS template
[author]
  name = "Robert van Bregt"
  url = "https://robertvanbregt.nl/"
  photo = "/images/photo.jpg"
  email = "contact@robertvanbregt.nl"
  note = """
    Ervaren projectmanager met <span alt="hart">❤️</span> voor digitale zorg.
    Echtgenoot en vader. Liefhebber van computers, technologie en wetenschap.
    Privacy-voorvechter. Buitensporter. Rotterdammert.
    """
  locality = "Capelle aan den IJssel"
  countryName = "Nederland"

[params]

  # ---------- common parameters ----------

 	author = "Robert van Bregt"
  description = "Persoonlijke website van Robert van Bregt"
  # description = "Verbetert de wereld en begint bij zichzelf."
  keywords = "blog, persoonlijk"

  favicon = "/favicon.ico"

  # Sections for home page content
  mainSections = ["article", "note"]

  # ---------- grotius theme ----------

  useLocalStyles = true

  # use Emoji instead of ForkAwesome icons
  useEmoji = false

  # inlinecss = false
  authorcard = true

  # ---------- coder theme ----------
  info = "Projectmanager. Automagiseerder. Geek. Rotterdammert."
  footerContent = "Verbetert de wereld en begint bij zichzelf."


  colorScheme = "auto"
  custom_css = []
  custom_js = []
  enableTwemoji = true

  # Series see also post count
  maxSeeAlsoItems = 5

  dateFormat = "2 January 2006"

  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2003

  commit = "https://github.com/metbril/robertvanbregt.nl/tree/"

  rtl = false

  math = false

  # ---------- other stuff ----------

  [[params.social]]
      name = "LinkedIn"
      icon = "fa fa-linkedin fa-2x"
      weight = 1
      url = "https://www.linkedin.com/in/robertvanbregt/"
      rel = "me"
      color = "#0077b5"
  [[params.social]]
      name = "Twitter"
      icon = "fa fa-twitter fa-2x"
      weight = 2
      url = "https://twitter.com/robertvanbregt/"
      rel = "me"
      color = "#1da1f2"
  [[params.social]]
      name = "Mastodon"
      icon = "fa fa-mastodon fa-2x"
      weight = 3
      url = "https://mastodon.social/@metbril"
      rel = "me"
      color = "#2b90d9"
  [[params.social]]
      name = "Github"
      icon = "fa fa-github fa-2x"
      weight = 11
      url = "https://github.com/metbril/"
      rel = "me"
      color = "#4183c4"
  [[params.social]]
      name = "Gitlab"
      icon = "fa fa-gitlab fa-2x"
      weight = 12
      url = "https://gitlab.com/metbril/"
      rel = "me"
      color = "#e2432a"
  [[params.social]]
      name = "Instagram"
      icon = "fa fa-instagram fa-2x"
      weight = 21
      url = "https://instagram.com/robertvanbregt/"
      rel = "me"
      color = "#c32aa3"
  [[params.social]]
      name = "Flickr"
      icon = "fa fa-flickr fa-2x"
      weight = 22
      url = "https://flickr.com/photos/rtvb/"
      rel = "me"
      color = "#f40083"
  [[params.social]]
      name = "Pocket"
      icon = "fa fa-get-pocket fa-2x"
      weight = 31
      url = "https://getpocket.com/@metbril"
      rel = "me"
      color = "#ee4056"
  [[params.social]]
      name = "Reddit"
      icon = "fa fa-reddit fa-2x"
      weight = 32
      url = "https://www.reddit.com/user/digineut"
      rel = "me"
      color = "#ff4500"
  [[params.social]]
      name = "Telegram"
      icon = "fa fa-telegram fa-2x"
      weight = 33
      url = "https://t.me/robertvanbregt"
      rel = "me"
      color = "#0088cc"
  [[params.social]]
      name = "Trello"
      icon = "fa fa-trello fa-2x"
      weight = 33
      url = "https://trello.com/metbril"
      rel = "me"
  [[params.social]]
      name = "E-mail"
      icon = "fa fa-gnupg fa-2x"
      weight = 97
      url = "/key.asc"
      color = "#0093DD"
  [[params.social]]
      name = "E-mail"
      icon = "fa fa-envelope fa-2x"
      weight = 98
      url = "mailto:contact@robertvanbregt.nl"
      rel = "me"
  [[params.social]]
      name = "RSS"
      icon = "fa fa-rss fa-2x"
      weight = 99
      url = "/index.xml"
      rel = "alternate"
      type = "application/rss+xml"
      color = "#f26522"

  [[params.indieweb.endpoint]]
    rel = "authorization_endpoint"
    url = "https://indieauth.com/auth"
  [[params.indieweb.endpoint]]
    rel = "token_endpoint"
    url = "https://tokens.indieauth.com/token"
  [[params.indieweb.endpoint]]
    rel = "webmention"
    url = "https://webmention.io/robertvanbregt.nl/webmention"
  [[params.indieweb.endpoint]]
    rel = "pingback"
    url = "https://webmention.io/robertvanbregt.nl/xmlrpc"
  [[params.indieweb.endpoint]]
    rel = "micropub"
    url = ""
  [[params.indieweb.endpoint]]
    rel = "microsub"
    url = ""

  [[params.posttype]]
    name = "article"
    icon = "fa fa-file-text-o fa-fw fa-lg"
  [[params.posttype]]
    name = "notes"
    icon = "fa fa-sticky-note fa-fw"
  [[params.posttype]]
    name = "bookmark"
    icon = "fa fa-bookmark fa-fw"

[menu]

  [[menu.main]]
    name = "Projecten"
    weight = 100
    url = "/projecten"
  [[menu.main]]
    name = "Over"
    weight = 180
    url = "/over"
  [[menu.main]]
    name = "Contact"
    weight = 190
    url = "/contact"

# language overrides
[languages]

    [languages.nl] # stub
      languageName = "nl 🇳🇱"
      paginatePath = "pagina"

    [languages.en]
        languageName = "en 🇺🇸"

        info = "Project manager. Automagician. Geek. Rotterdamned."
        description = "Personal website of Robert van Bregt"
        keywords = "blog, personal"
        footerContent = "Improves the world and starts with himself."

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 10
            url = "/posts"

            [[languages.en.menu.main]]
            name = "About"
            weight = 30
            url = "/about"

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 40
            url = "/contact"

# explicitly specify taxonomies for coder theme which supports series
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  # Specify for each section (= folder name)
  article = "/:year/:month/:day/:slug/"
  bladwijzers = "/:year/:month/:day/:slug/"
  likes = "/:year/:month/:day/:slug/"
  notes = "/:year/:month/:day/:slug/"
  reacties = "/:year/:month/:day/:slug/"
  rsvps = "/:year/:month/:day/:slug/"
  # https://gohugo.io/content-management/urls/#permalink-configuration-values
  # :year        | the 4-digit year
  # :month       | the 2-digit month
  # :monthname   | the name of the month
  # :day         | the 2-digit day
  # :weekday     | the 1-digit day of the week (Sunday = 0)
  # :weekdayname | the name of the day of the week
  # :yearday     | the 1- to 3-digit day of the year
  # :section     | the content’s section
  # :sections    | the content’s sections hierarchy
  # :title       | the content’s title
  # :slug        | the content’s slug (or title if no slug is provided in the front matter)
  # :filename    | the content’s filename (without extension)

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[services.rss]
  limit = 10