baseURL = "http://www.robertvanbregt.nl/"
languageCode = "nl-nl"
title = "Robert van Bregt"
theme = "ananke"
copyright = "CC International"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "/favicon.ico"
  description = "Verbetert de wereld, maar begint bij zichzelf."
  twitter = "https://twitter.com/robertvanbregt"
  instagram = "https://instagram.com/robertvanbregt"
  youtube = ""
  github = "https://github.com/metbril"
  gitlab = "htps://gitlab.com/metbril"
  medium = ""
  linkedin = "https://linkedin.com/in/robertvanbregt"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
  # avatar = 'img/avatar.png'
  # avatar = 'https://s.gravatar.com/avatar/951332480630db814aa03e362f2eb5cb?s=150'
