baseURL = "https://www.robertvanbregt.nl/"
title = "Robert van Bregt"
languageCode = "nl-nl"
copyright = "Tenzij anders aangegeven valt de inhoud van deze website onder een Creative Commons Naamsvermelding-GelijkDelen 4.0 Internationaal-licentie."
theme = "grotius"

paginate = 20
paginatePath = "pagina"

pluralizeListTitles = false

MetaDataFormat = "yaml"
DefaultContentLanguage = "nl"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "Home"
    url = "/"
    weight = -1

[params]
  description = "Verbetert de wereld, maar begint bij zichzelf."
  mainSections = ["article", "note", "like", "bookmark"]     # sections on homepage
  favicon = "/favicon.ico"
  images = ["/images/photo.jpg"]

  # Grotius theme
  localStyles = true
  # author = "Robert van Bregt"

# grotius: h-card properties
[params.author]
  name = "Robert van Bregt"
  url = "https://robertvanbregt.nl"
  photo = "/images/photo.jpg"
  email = "contact@robertvanbregt.nl"
  locality = "Capelle aan den IJssel"
  countryName = "Nederland"
  note = "Projectmanager. Echtgenoot en vader. Nerd. Rotterdammert."

# grotius: IndieWeb Endpoints
[params.indieweb]
    AuthorizationEndpoint = "https://indieauth.com/auth"    # default 'https://indieauth.com/auth'
    TokenEndpoint = "https://tokens.indieauth.com/token"    # default 'https://tokens.indieauth.com/token'
    Micropub = "https://indiekit-robertvanbregt.herokuapp.com/micropub"
    Microsub = "https://aperture.p3k.io/microsub/79"
    Webmention = "https://webmention.io/robertvanbregt.nl/webmention"
    Pingback = "https://webmention.io/robertvanbregt.nl/xmlrpc"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[permalinks]
  artikelen = "/:year/:month/:day/:slug/"
  bladwijzers = "/:year/:month/:day/:slug/"
  notities = "/:year/:month/:day/:slug/"
  likes = "/:year/:month/:day/:slug/"
  reacties = "/:year/:month/:day/:slug/"
  rsvps = "/:year/:month/:day/:slug/"
  # https://gohugo.io/content-management/urls/#permalink-configuration-values
  # :year        | the 4-digit year
  # :month       | the 2-digit month
  # :monthname   | the name of the month
  # :day         | the 2-digit day
  # :weekday     | the 1-digit day of the week (Sunday = 0)
  # :weekdayname | the name of the day of the week
  # :yearday     | the 1- to 3-digit day of the year
  # :section     | the content’s section
  # :sections    | the content’s sections hierarchy
  # :title       | the content’s title
  # :slug        | the content’s slug (or title if no slug is provided in the front matter)
  # :filename    | the content’s filename (without extension)

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
