# Base url is overwritten in netlify.toml
baseUrl   = "https://new.vanbregt.eu/"
defaultContentLanguage = "en"
title = "Robert van Bregt"

# copyright is used in internal RSS template
# https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml
copyright = "© Copyright 2003-2024 Robert van Bregt"

theme = "grotius"

enableEmoji = true

# Lazy menu
# sectionPagesMenu = "main"

# The sections which content is included in the home page
mainSections = [ "posts" ]

##################################################

# archetypeDir  = "archetypes"
# assetDir      = "assets"
# contentDir    = "content"
# configDir     = "config"
# datadir       = "data"
# layoutDir     = "layouts"
# publishDir    = "public"
# staticDir     = "static"
# themesDir     = "themes"

##################################################

# pagination
paginate     = 10         # default = 10
paginatePath = "pagina"   # default = "page"

summaryLength = 70  # default 70 (words)

canonifyUrls = true

pluralizeListTitles = false

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = ""
googleAnalytics = ""

# content front matter format
metaDataFormat = "yaml"

enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  name = "Posts"
  pageRef = "posts"
  weight = 1

[[menu.main]]
  name =  "About"
  pageRef = "about"
  weight = 10

[[menu.main]]
  name = "Contact"
  pageRef = "contact"
  weight = 190

[params]

  # ---------- official and common parameters ----------

  # author      = "Robert van Bregt"
  description = "Persoonlijke website van Robert van Bregt"
  keywords    = "blog, persoonlijk"
  images      = ["/img/avatar.jpg"]  # twitter cards
  avatarURL   = "/img/avatar.jpg"
  favicon     = "/favicon.ico"

  # dateFormat = "2 January 2006"
  dateFormat = "02-01-2006"

  # "See also" post count
  maxSeeAlsoItems = 5

  commit = "https://codeberg.org/r12t/home/commit/"

  rtl    = false

  math   = false

  # some markdown allowed
  license = "Unless otherwise noted, all written content on this site is licenced with a [CC BY-SA 4.0 license](http://creativecommons.org/licenses/by-sa/4.0/)."

  [params.author]
    # name and email are used in internal RSS template
    # https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml
    name  = "Robert van Bregt"
    email = "contact.rjib@vanbregt.eu"

    # custom properties
    url   = "https://www.vanbregt.eu/"
    photo = "/img/photo.jpg"

  # [params.social]
  #   # Twitter meta card
  #   twitter = "robertvanbregt"

[permalinks]
  # Specify for each section (= folder name)
  posts = "/:year/:month/:day/:slugorfilename/"

  # https://gohugo.io/content-management/urls/#permalink-configuration-values
  # :year        | the 4-digit year
  # :month       | the 2-digit month
  # :monthname   | the name of the month
  # :day         | the 2-digit day
  # :weekday     | the 1-digit day of the week (Sunday = 0)
  # :weekdayname | the name of the day of the week
  # :yearday     | the 1- to 3-digit day of the year
  # :section     | the content’s section
  # :sections    | the content’s sections hierarchy
  # :title       | the content’s title
  # :slug        | the content’s slug (or title if no slug is provided in the front matter)
  # :filename    | the content’s filename (without extension)

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[services.rss]
  limit = 10

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# explicitly specify taxonomies for series support
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

