# Base url is overwritten in netlify.toml
baseUrl   = "https://vanbregt.eu/"
defaultContentLanguage = "en"
title = "Robert van Bregt"

# copyright is used in internal RSS template
# https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml
copyright = "© Copyright 2003-2024 Robert van Bregt"

theme = "hugo-simple"

enableEmoji = true

# https://github.com/gohugoio/hugo/issues/12152
capitalizeListTitles = false

# Lazy menu
# sectionPagesMenu = "main"

# The sections which content is included in the home page
mainSections = [ "posts" ]

##################################################

# archetypeDir  = "archetypes"
# assetDir      = "assets"
# contentDir    = "content"
# configDir     = "config"
# datadir       = "data"
# layoutDir     = "layouts"
# publishDir    = "public"
# staticDir     = "static"
# themesDir     = "themes"

##################################################

summaryLength = 70  # default 70 (words)

canonifyUrls = true

pluralizeListTitles = false

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = ""
googleAnalytics = ""

# content front matter format
metaDataFormat = "yaml"

enableRobotsTXT = true

[pagination]
pagerSize = 10        # default = 10
path      = "pagina"  # default = "page"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Give homepage weight -1 to force it before unweighed entries
[[menu.main]]
  name = "Home"
  pageRef = "/"
  weight = -1

[[menu.main]]
  name = "Posts"
  pageRef = "posts"
  weight = 1

[[menu.main]]
  name = "Categories"
  pageRef = "categories"
  weight = 2

[[menu.main]]
  name = "Tags"
  pageRef = "tags"
  weight = 3

[[menu.main]]
  name =  "About"
  pageRef = "about"
  weight = 10

[[menu.main]]
  name = "Contact"
  pageRef = "/contact"
  weight = 190

[[menu.footer]]
  name = "privacy"
  url = "/legal/#privacy"
  weight = 11

[[menu.footer]]
  name = "license"
  url = "/legal/#license"
  weight = 12

[[menu.footer]]
  name = "more legal..."
  pageRef = "/legal/"
  weight = 19

[[menu.footer]]
  name = "follow"
  pageRef = "/follow/"
  weight = 98

[[menu.footer]]
  name = "rss"
  url = "/index.xml"
  weight = 999

[params]

  # ---------- official and common parameters ----------

  # author      = "Robert van Bregt"
  description = "Persoonlijke website van Robert van Bregt"
  keywords    = "blog, persoonlijk"
  images      = ["/img/avatar.jpg"]  # twitter cards
  avatarURL   = "/img/avatar.jpg"
  favicon     = "/favicon.ico"

  # dateFormat = "2 January 2006"
  dateFormat = "02-01-2006"

  # "See also" post count
  maxSeeAlsoItems = 5

  commit = "https://codeberg.org/r12t/home/commit/"

  rtl    = false

  math   = false

  # some markdown allowed
  license = "Unless otherwise noted, all written content on this site is licenced with a [CC BY-SA 4.0 license](http://creativecommons.org/licenses/by-sa/4.0/)."

  ##### Grotius v2
  # the number of recent posts on the homepage
  recentPosts = 7 # default = 5
  hideCredits = false  # default = false

  [params.author]
    # name and email are used in internal RSS template
    # https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml
    name  = "Robert van Bregt"
    email = "contact.rjib@vanbregt.eu"

    # custom properties
    url   = "https://www.vanbregt.eu/"
    photo = "/img/photo.jpg"

  # [params.social]
  #   # Twitter meta card
  #   twitter = "robertvanbregt"

  ##### Grotius v2
  # Content-Security-Policy
  # Codeberg does not allow you to set HTTP headers, so let's add them to the page head.
  # https://content-security-policy.com/examples/meta/
  # https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP
  [params.csp]
    childsrc = ["'self'"]
    fontsrc = ["'self'"]
    formaction = ["'self'"]
    framesrc = [
      "'self'", 
      "https://www.youtube.com", 
    ]
    imgsrc = [
      "'self'",
    ]
    objectsrc = ["'none'"]
    stylesrc = [
      "'self'",
      "'unsafe-inline'"
    ]
    scriptsrc = [
      "'self'",
      "'unsafe-inline'",
    ]
    connectsrc = [
      "'self'"
    ]

[permalinks]
  # Specify for each section (= folder name)
  posts = "/:year/:month/:day/:slugorfilename/"

  # https://gohugo.io/content-management/urls/#permalink-configuration-values
  # :year        | the 4-digit year
  # :month       | the 2-digit month
  # :monthname   | the name of the month
  # :day         | the 2-digit day
  # :weekday     | the 1-digit day of the week (Sunday = 0)
  # :weekdayname | the name of the day of the week
  # :yearday     | the 1- to 3-digit day of the year
  # :section     | the content’s section
  # :sections    | the content’s sections hierarchy
  # :title       | the content’s title
  # :slug        | the content’s slug (or title if no slug is provided in the front matter)
  # :filename    | the content’s filename (without extension)

[privacy]
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[services.rss]
  limit = 10

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# explicitly specify taxonomies for series support
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
