[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.62.2"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
HUGO_ENV = "develop"
HUGO_ENABLEGITINFO = "true"
HUGO_VERSION = "0.62.2"
