[build]
publish = "public"
command = "hugo"

[context.production]
#command = "hugo --baseURL $URL"
#command = "hugo --baseURL $DEPLOY_URL"
command = "hugo --baseURL $DEPLOY_PRIME_URL"

[context.production.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.62.2"
HUGO_ENABLEGITINFO = "true"

[context.branch-deploy]
command = "hugo --buildFuture --buildDrafts --baseURL $DEPLOY_URL"

[context.branch-deploy.environment]
HUGO_ENV = "develop"
HUGO_ENABLEGITINFO = "true"
HUGO_VERSION = "0.62.2"
