# lint.yml

when:
  # Exclude pipeline to be run on "pages" branch
  - event: push
    branch:
      exclude: pages

clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      recursive: false

steps:
  lint-markdown:
    image: davidanson/markdownlint-cli2:latest
    commands:
      - markdownlint-cli2 "content/**/*.{md,markdown}"
    when:
      - path: 'content/**/*.md'
    depends_on: []

  spell:
    image: ghcr.io/streetsidesoftware/cspell:latest
    commands:
      - npm install -g @cspell/dict-nl-nl
      - cspell-cli link add @cspell/dict-nl-nl
      - cspell-cli --locale "nl,en-GB" --no-progress "content/**/*.{md,markdown}"
    when:
      - path: 'content/**/*.{md,markdown}'
    depends_on: []
